duckInstrument.Piano=Пианино
duckInstrument.AutoPlaying=Сейчас играет: %q
duckInstrument.Space=Пробел - Нотные листы
duckInstrument.Tab1=Tab - Прекратить Авто-игру | Ctrl - Говорить
duckInstrument.Tab2=Tab - Выйти из инструмента | Alt - Авто-игра | Ctrl - Говорить
duckInstrument.Tab2_NoAutoplay=Tab - Выйти из инструмента | Ctrl - Говорить
duckInstrument.Songs=Песни
duckInstrument.SongList=Список песен