duckInstrument.Category=Duck Instruments
duckInstrument.Piano=Piano
duckInstrument.AutoPlaying=Auto-playing %q
duckInstrument.Space=Space for sheet music
duckInstrument.Tab1=Tab to stop auto-playing | Ctrl to toggle microphone
duckInstrument.Tab2=Tab to leave The instrument | Alt for auto-play mode | Ctrl to toggle microphone
duckInstrument.Tab2_NoAutoplay=Tab to leave The instrument | Ctrl to toggle microphone
duckInstrument.Songs=Songs
duckInstrument.SongList=Song List